# Site settings
title: 曹立
header-img: img/home-bg.jpg
email: oos1111@sjtu.edu.cn
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "Irving-cl.github.io"
github_username:  Irving-cl

email_username:  oos1111@sjtu.edu.cn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
