# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Irving's blog
header-img: img/home-bg.jpg
email: oos111l@sjtu.edu.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "Irving-cl.github.io" # the base hostname & protocol for your site
github_username:  Irving-cl
email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]