# Site settings
title: 曹立
description: '我的个人主页'
url: '' 
#'http://joshgerdes.com/jekyll-uno' 
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'

author:
  name: '曹立'
  email: oos1111@sjtu.edu.cn
  twitter_username: Irving__cl
  github_username: Irving_cl
  linkedin_username: 曹立

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']